version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: wizzn/keycloak:14
    command:
      - "-b"
      - "0.0.0.0"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=kcuser
      - DB_PASSWORD=kcuser1234
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
    ports:
      - "8083:8080"
    depends_on:
      - db
volumes:
  db:
    driver: local