version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: wizzn/keycloak:14
    command:
      - "-b"
      - "0.0.0.0"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=kcuser
      - DB_PASSWORD=kcuser1234
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
    ports:
      - "8083:8080"
    depends_on:
      - db
  collector:
    image: otel/opentelemetry-collector:0.47.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - .configuration/open-telemetry/otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger-service
  jaeger-service:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"
volumes:
  db:
    driver: local