version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8083:8080"
  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  db:
    driver: local