spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://localhost:8083/auth/realms/ecommerce
          jwkSetUri: http://localhost:8083/auth/realms/ecommerce/protocol/openid-connect/certs