{{- if .Values.keycloak.istio.enabled -}}
{{- if .Values.keycloak.istio.security.enabled -}}
{{- $serviceName := include "keycloak.fullname" . -}}
{{- $servicePort := .Values.keycloak.service.httpPort -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "keycloak.fullname" . }}-keycloak-gateway
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "ecommerce.chart" . }}
spec:
  selector:
    istio: {{ .Values.keycloak.istio.gateway }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
    {{- if eq .Values.keycloak.istio.protocol "https" }}
      tls:
        httpsRedirect: true
    {{- end }}
      hosts:
        {{- range .Values.keycloak.istio.hosts }}
        - {{ .host }}
        {{- end }}
  {{- if eq .Values.istio.protocol "https" }}
    - hosts:
       {{- range .Values.keycloak.istio.hosts }}
        - {{ .host }}
       {{- end }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: "sds"
        privateKey: "sds"
        credentialName: {{ .Values.keycloak.istio.security.credentialName }}
  {{- end }}
{{- end }}
{{- end }}