scrape_configs:
  - job_name: 'E-Commerce Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['docker.for.mac.localhost:8081'] #docker.for.mac.localhost #host.docker.internal
        labels:
          application: 'My Spring Boot Application'