version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: monitoring-prometheus
    volumes:
      - .configuration/monitoring:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - '9090:9090'
    expose:
      - 9090
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: monitoring-grafana
    volumes:
      - .data/grafana_data:/var/lib/grafana
      - .data/grafana/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000
    labels:
      org.label-schema.group: "monitoring"