spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

keycloak:
  enabled: true
  realm: master
  auth-server-url: http://localhost:8083/auth
  ssl-required: external
  resource: ecommerce
  use-resource-role-mappings: true
  enable-basic-auth: true
