spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: http://localhost:8083/auth/realms/master
          jwkSetUri: http://localhost:8083/auth/realms/master/protocol/openid-connect/certs