spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8083}/realms/master
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
  data:
    redis:
      host: localhost
      port: 6379
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*" # openapi, swagger-ui
  prometheus:
    metrics:
      export:
        enabled: true
springdoc:
  use-management-port: true
  show-actuator: true
  enable-spring-security: true

ecommerce:
  mail:
    from:
  storage:
    s3:
      access-key:
      secret-key:
      bucket-name:
      region:
      endpoint:
  payment:
    stripe:
      public-key:
      secret-key:
