name: Package and Publish Helm Chart
on:
  push:
    paths:
      - .helm-chart/**
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  helm-chart:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: DragomirAlin/helm-charts
          token: ${{ secrets.BOT_GH_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: helm-charts
      - name: Helm Package
        run: helm package .helm-chart --version "0.0.1+dev" -d helm-charts
      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
        run: |
          git config --global user.email "bot@dragomiralin.ro"
          git config --global user.name "Helm Bot"
          CHART_PACKAGE_NAME="ecommerce-0.0.1+dev.tgz"
          cd helm-charts
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main